carts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

sokoMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')), # new  
    path('store/', include('store.urls')), # new
    path('cart', include('carts.urls')), # new
    path('accounts/', include('accounts.urls')), # new
    path('orders/', include('orders.urls')), # new
    path('appointment/', include('appointment.urls')), # new
    path('supplier/', include('supplier.urls')), # new
    path('feedback/', include('feedback.urls')), # new
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/product/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

store/models.py
from django.db import models
from django.urls import reverse


from category.models import Category
from accounts.models import Account

class Product(models.Model):
    product_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    product_description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.product_name
    
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])
    
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True)
        average = reviews.aggregate(average=models.Avg('rating'))
        avg = 0
        if average['average'] is not None:
            avg = float(average['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=models.Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)
    

variation_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)    

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    
    objects = VariationManager()
    
    def __str__(self):
        return self.variation_value
    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.subject
    
class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products/', max_length=255)
    created_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.product.product_name
    
    class Meta:
        verbose_name = 'Product Gallery'
        verbose_name_plural = 'Product Gallery'

store/forms.py
from django import forms

from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.contrib import messages


from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.models import CartItem
from carts.views import _cart_id
from .forms import ReviewForm
from orders.models import OrderProduct

def store(request, category_slug=None):
    categories = None
    products = None
    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True).order_by('-created_date')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('-created_date')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)

def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        # check if the product is in the cart or not
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
        
    except Exception as e:
        raise e
    
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except orderproduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    # Get the product Gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct': orderproduct,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'store/product_detail.html', context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(product_description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count,
        
    }
    
    return render(request, 'store/store.html', context)

def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)
            else:
                print(form.errors)
                return redirect(url)
            

templates/store/product_detail.html
<!-- @format -->

{% extends 'base.html' %} 
{% block title %}{{single_product.product_name}}{%endblock %} 
{% load static %} 
{% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <div class="text-center">
                <img src="{{single_product.image.url}}"  alt="product image" class="img-fluid" style="max-width: 100%;" />
              </div> 
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <ul class="thumb">
            <li style="list-style: none;
            margin: 10px;">
            <a href="{{single_product.image.url}}" class="thumb-link" target="mainImage">
              <img src="{{single_product.image.url}}" alt="product gallery" style="width: 80px;
             height: 80px;
             border: 1px solid grey;" />
           </a>
              {% for i in product_gallery %}
              <a href="{{i.image.url}}" class="thumb-link" target="mainImage">
                 <img src="{{i.image.url}}" alt="product gallery" style="width: 80px;
                height: 80px;
                border: 1px solid grey;" />
              </a>
              {% endfor %}
            </li>
          </ul>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{single_product.product_name}}</h2>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
                  <span> {{single_product.countReview}} Reviews </span>
                </span>
              </div>
              

              <div class="mb-3">
                <var class="price h4"> {{single_product.price}} </var>
              </div>

              <p>{{single_product.product_description}}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select
                    name="color"
                    class="form-control-md form-control"
                    required
                  >
                    <option value="" selected disabled>Choose Color</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{ i.variation_value | lower}}">
                      {{ i.variation_value | capfirst }}
                    </option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" class="form-control-md form-control">
                    <option value="" selected disabled>Choose size</option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{ i.variation_value | lower }}">
                      {{ i.variation_value | capfirst }}
                    </option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h5 class="btn btn-danger">
                <span class="text">Out of stock</span>
                <i class="fas fa-shopping-cart"></i>
              </h5>
              {% else %}

              <button type="submit" class="btn btn-primary">
                <span class="text">Add to Cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %}
            </article>
            <!-- product-info-aside .// -->
          </form>
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        

        <form action="{% url 'submit_review' single_product.id %}" method="POST">
          {% csrf_token %}
          <h5> Write Your Review </h5>
         
          <div>
            <!--Rating stars-->
            <label>How do you rate this Product?</label>
            <br />
            <div class="rate">
              <input type="radio" class="rating" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
              <input type="radio" class="rating" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
              <input type="radio" class="rating" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
              <input type="radio" class="rating" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
              <input type="radio" class="rating" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
              <input type="radio" class="rating" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
              <input type="radio" class="rating" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
              <input type="radio" class="rating" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
              <input type="radio" class="rating" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
              <input type="radio" class="rating" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br />

            Review Title:
            <input type="text" class="form-control" name="subject">
            <br>
            Review:
            <textarea type="text" name="review"  rows="4" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
              {% if orderproduct %}
                <input type="submit" value="Submit Review" class="btn btn-primary">
              {% else %}
                <p> 
                  You must have purchased this product to submit a review.
                </p>
              {% endif %}
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary">Login to Submit Review</a>
            {% endif %}
           
          </div>
          
        </form>
        {% include 'includes/messages.html' %}
        <br>

        <header class="section-heading">
          <h3>Customer Reviews</h3> 
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
              <span> {{single_product.countReview}} Reviews </span>
            </span>
          </div>
        </header>

        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            
            <div class="text">
              <span class="date text-muted float-md-right">{{review.updated_at}} </span>
              <h6 class="mb-1"> {{review.user.full_name}} </h6>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
                </span>
              </div>
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <h6> {{review.subject}} </h6>
            <p>
              {{review.review}}
            </p>
          </div>
        </article>
        {% endfor %}
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<script>
  $(document).ready(function () {
    $(".thumb a").click(function (e) {
      e.preventDefault();
      $(".mainImage img").attr("src", $(this).attr("href"));
    });
  });
</script>
{% endblock %}

templates/store/store.html
<!-- @format -->

{% extends 'base.html' %} {% load static %} {% block title %}Store{% endblock %}
{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  <div class="container">
    {% if 'search' in request.path %}
    <h2 class="title-page">Search Results</h2>
    {% else %}
    <h2 class="title-page">Our Store</h2>
    {% endif %}
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <div class="card">
          <article class="filter-group">
            <header class="card-header">
              <a
                href="#"
                data-toggle="collapse"
                data-target="#collapse_1"
                aria-expanded="true"
                class=""
              >
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title">Categories</h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
              <div class="card-body">
                <ul class="list-menu">
                  <li><a href="{% url 'store' %}"> All Products </a></li>
                  {% for category in links %}
                  <li>
                    <a href="{{category.get_url}}">
                      {{category.category_name}}
                    </a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
              <!-- card-body.// -->
            </div>
          </article>
          <!-- filter-group  .// -->
          

          
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <main class="col-md-9">
        <header class="border-bottom mb-4 pb-3">
          <div class="form-inline">
            <span class="mr-md-auto"
              ><b>{{product_count}}</b> Items found
            </span>
          </div>
        </header>
        <!-- sect-heading -->

        <div class="row">
          {% if products %} 
          {% for product in products %}
          <div class="col-md-4">
            <figure class="card card-product-grid">
              <div class="img-wrap">
                <a href="{{product.get_url}}">
                  <img src="{{product.image.url}}" />
                </a>
              </div>
              <!-- img-wrap.// -->
              <figcaption class="info-wrap">
                <div class="fix-height">
                  <a href="{{product.get_url}}" class="title">
                    {{product.product_name}}
                  </a>
                  <div class="price-wrap mt-2">
                    <span class="price"> $ {{product.price}} </span>
                  </div>
                  <!-- price-wrap.// -->
                  <div class="rating-star">
                    <span>
                      <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
                      <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
                      
                    </span>
                  </div>
                </div>
                <a href="{{product.get_url}}" class="btn btn-block btn-primary"
                  >View Details</a
                >
              </figcaption>
            </figure>
          </div>
          <!-- col.// -->
          {% endfor %} 
          {% else %}
          <div class="col-md-12">
            <h3>No Products Found</h3>
          </div>
          {% endif %}
        </div>
        <!-- row end.// -->

        <nav class="mt-4" aria-label="Page navigation sample">
          {% if products.has_other_pages %}
          <ul class="pagination">
            {% if products.has_previous %}
            <li class="page-item">
              <a
                data-page="{{products.previous_page_number}}"
                class="page-link"
                href="?page={{products.previous_page_number}}"
                >Previous</a
              >
            </li>
            {% endif %} 
            {% for i in products.paginator.page_range %} 
            {% if products.number == i %}
            <li class="page-item active">
              <a class="page-link" href="?page={{i}}"> {{i}} </a>
            </li>
            {% else %}

            <li class="page-item">
              <a class="page-link" href="?page={{i}}"> {{i}} </a>
            </li>
            {% endif %} 
            {% endfor %} 
            {% if products.has_next %}
            <li class="page-item">
              <a
                data-page="{{products.num_pages}}"
                class="page-link"
                href="?page={{products.next_page_number}}"
                >Next</a
              >
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
      <!-- col.// -->
    </div>
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}