carts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

feedback/urls.py
from django.urls import path
from feedback.views import leave_feedback


urlpatterns = [
    path('feedbacks/', leave_feedback, name='feedback'),
]

sokoMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')), # new  
    path('store/', include('store.urls')), # new
    path('cart', include('carts.urls')), # new
    path('accounts/', include('accounts.urls')), # new
    path('orders/', include('orders.urls')), # new
    path('appointment/', include('appointment.urls')), # new
    path('supplier/', include('supplier.urls')), # new
    path('feedback/', include('feedback.urls')), # new
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

feedback/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import Account



class BaseFeedback(models.Model):
    type = models.CharField(choices=settings.FEEDBACK_CHOICES, max_length=100,
                            verbose_name=_('Type'))
    message = models.TextField(verbose_name=_('Message'))
    time = models.DateTimeField(auto_now_add=True, verbose_name=_('Time'))

    class Meta:
        abstract = True
        ordering = ['-time']

    def __unicode__(self):
        return self.message


class Feedback(BaseFeedback):
    user = models.ForeignKey(Account, verbose_name=_('User'), on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('admin:view-feedback', args=[self.id])


class AnonymousFeedback(BaseFeedback):
    user = models.ForeignKey(Account, verbose_name=_('User'), null=True,
                             blank=True, default=None, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('admin:view-anon-feedback', args=[self.id])

feedback/forms.py
from django import forms
from feedback.models import AnonymousFeedback, Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)

        # Add placeholders and classes to form inputs
        self.fields['message'].widget.attrs['placeholder'] = 'Enter You feedback here'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    



class AnonymousFeedbackForm(forms.ModelForm):
    class Meta:
        model = AnonymousFeedback
        exclude = ('user',)

feedback/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from feedback.forms import AnonymousFeedbackForm, FeedbackForm

def leave_feedback(request):
    if request.user.is_authenticated:
        form = FeedbackForm(request.POST or None)
    else:
        form = AnonymousFeedbackForm(request.POST or None)
    if form.is_valid():
        feedback = form.save(commit=False)
        if request.user.is_anonymous:
            feedback.user = None
        else:
            feedback.user = request.user
        feedback.save()
        messages.add_message(request, messages.SUCCESS,
                             'Your feedback was submitted.')
        return HttpResponseRedirect(request.POST.get('next',
                                    request.META.get('HTTP_REFERER', '/')))
    return render(request, 'feedback/feedback_form.html', {'feedback_form': form})

templates/feedback/feedback_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Leave some feedback{% endblock %}
{% block content %}
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ feedback_form.as_p }}
            <div>
                <div class="form-control" colspan='2'>
                    <input class="btn btn-primary" type="submit" value="Leave feedback" />
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/feedback/index.html
{% extends "admin/index.html" %}
{% load i18n feedback_tags %}
{% block extrahead %}
    <style type='text/css'>
    #feedback {float:right;margin-right:-38em;width:18em;position:relative;}
    </style>
    {{ block.super }}
{% endblock %}
{% block sidebar %}
    {{ block.super }}
    <div id="feedback">
        <div class="module" id="feedback-module">
            <h2>{% trans 'Feedback' %}</h2>
            <ul class='actionlist'>
                {% get_feedback %}
                {% for feedback in feedback %}
                    <li><a href="{{ feedback.get_absolute_url }}">{{ feedback.get_type_display }} from {% firstof feedback.user.username "anon" %}</a> &mdash; {{ feedback.time|timesince }} ago</li>
                {% endfor %}
            </ul>
            <p><a href="{% url 'admin:feedback_feedback_changelist' %}">View all feedback</a></p>
        </div>
    </div>
{% endblock %}

templates/feedback/view_feedback.html
{% extends "admin/change_form.html" %}
{% load i18n %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../../">{% trans "Feedback" %}</a> &rsaquo; 
     Viewing Feedback
</div>
{% endif %}{% endblock %}
{% block content %}
    <div id="content-main">
        <fieldset class="module aligned">
            <h2>{{ feedback.get_type_display }} from {{ feedback.user|title }} &mdash; {{ feedback.time|timesince }} ago</h2>
            <p>{{ feedback.message }}</p>
            <h3>Actions</h3>
            <ul>
                <li><a href='mailto:{{ feedback.user.email }}'>E-mail user</a></li>
                <li><a href='../../{{ feedback.id }}/'>Edit Feedback</a></li>
                <li><a href='../../{{ feedback.id }}/delete/'>Delete Feedback</a></li>
            </ul>
        </fieldset>
    </div>
{% endblock %}